apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: cleanup
spec:
  workspaces:
    - name: source
  steps:
    - name: cleanup
      image: alpine:3.20
      script: |
        #!/bin/sh
        echo "Cleaning workspace..."
        rm -rf /workspace/source/__pycache__
        rm -rf /workspace/source/.pytest_cache

---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: test
spec:
  workspaces:
    - name: source
  steps:
    - name: test
      image: python:3.11
      workingDir: /workspace/source
      script: |
        #!/bin/bash
        set -e

        echo "Installing dependencies..."
        pip install --upgrade pip
        pip install flake8 nose

        echo "Running flake8..."
        flake8 .

        echo "Running unit tests..."
        nosetests